[project]
name = "mcptutorial"
version = "0.1.0"
description = "MCP tutorials using FastMCP"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.14.2",
    "httpx>=0.28.1",
]

[project.scripts]
run-server = "brent_bin_day_agent:main"
