[project]
name = "mcptutorial"
version = "0.1.0"
description = "MCP tutorials using FastMCP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.21.2",
]

[project.scripts]
run-server = "main:main"
